<?php

$LOGINUSER_TABLE = 'LOGINUSER';

$LOGINUSER_USERID = 'USERID';
$LOGINUSER_LOGINNAME = 'LOGINNAME';
$LOGINUSER_PASSWORD = 'PASSWORD';
$LOGINUSER_TYPE = 'TYPE';
$LOGINUSER_STATUS = 'STATUS';
$LOGINUSER_EMAIL = 'EMAIL';
$LOGINUSER_SECQUESTION = 'SECQUESTION';
$LOGINUSER_SECANSWER = 'SECANSWER';
$LOGINUSER_CREATEDON = 'CREATEDON';
$LOGINUSER_MODIFIEDON = 'MODIFIEDON';
$LOGINUSER_MODIFIEDBY = 'MODIFIEDBY';


$USERTYPE_TABLE = 'USERTYPE';

$USERTYPE_TYPEID = 'TYPEID';
$USERTYPE_TYPEDESCRIPTION = 'TYPEDESCRIPTION';


$USERSTATUS_TABLE = 'USERSTATUS';

$USERSTATUS_STATUSID = 'STATUSID';
$USERSTATUS_STATUSDESCRIPTION = 'STATUSDESCRIPTION';


$JOBSEEKER_TABLE = 'JOBSEEKER';

$JOBSEEKER_JOBSKID = 'JOBSKID';
$JOBSEEKER_FNAME = 'FNAME';
$JOBSEEKER_MNAME = 'MNAME';
$JOBSEEKER_LASTNAME = 'LASTNAME';
$JOBSEEKER_ADDRESS1 = 'ADDRESS1';
$JOBSEEKER_ADDRESS2 = 'ADDRESS2';
$JOBSEEKER_CITY = 'CITY';
$JOBSEEKER_STATE = 'STATE';
$JOBSEEKER_POSTALCODE = 'POSTALCODE';
$JOBSEEKER_COUNTRY = 'COUNTRY';
$JOBSEEKER_GENDER = 'GENDER';
$JOBSEEKER_PHONE = 'PHONE';
$JOBSEEKER_CREATEDON = 'CREATEDON';
$JOBSEEKER_MODIFIEDON = 'MODIFIEDON';
$JOBSEEKER_MODIFIEDBY = 'MODIFIEDBY';


$USERGENDER_TABLE = 'USERGENDER';

$USERGENDER_GENDERID = 'GENDERID';
$USERGENDER_GENDERDESCRIPTION = 'GENDERDESCRIPTION';


$EMPLOYER_TABLE = 'EMPLOYER';

$EMPLOYER_EMPLOYERID = 'EMPLOYERID';
$EMPLOYER_FNAME = 'FNAME';
$EMPLOYER_MNAME = 'MNAME';
$EMPLOYER_LASTNAME = 'LASTNAME';
$EMPLOYER_ADDRESS1 = 'ADDRESS1';
$EMPLOYER_ADDRESS2 = 'ADDRESS2';
$EMPLOYER_CITY = 'CITY';
$EMPLOYER_STATE = 'STATE';
$EMPLOYER_POSTALCODE = 'POSTALCODE';
$EMPLOYER_COUNTRY = 'COUNTRY';
$EMPLOYER_PHONE1 = 'PHONE1';
$EMPLOYER_PHONE2 = 'PHONE2';
$EMPLOYER_FAXNO = 'FAXNO';
$EMPLOYER_CREATEDON = 'CREATEDON';
$EMPLOYER_MODIFIEDON = 'MODIFIEDON';
$EMPLOYER_MODIFIEDBY = 'MODIFIEDBY';


$JOBS_TABLE = 'JOBS';

$JOBS_JOBID = 'JOBID';
$JOBS_EMPLOYERID = 'EMPLOYERID';
$JOBS_JOBTITLE = 'JOBTITLE';
$JOBS_DESIGNATION = 'DESIGNATION';
$JOBS_SECTOR = 'SECTOR';
$JOBS_EXPERIENCE = 'EXPERIENCE';
$JOBS_LOCATION = 'LOCATION';
$JOBS_SALARY = 'SALARY';
$JOBS_POSITIONS = 'POSITIONS';
$JOBS_QUALIFICATION = 'QUALIFICATION';
$JOBS_NOTICEPERIOD = 'NOTICEPERIOD';
$JOBS_ADDSKILLS = 'ADDSKILLS';
$JOBS_JOBPOSTEDON = 'JOBPOSTEDON';
$JOBS_INTERVIEWTYPE = 'INTERVIEWTYPE';
$JOBS_JOBSTATUS = 'JOBSTATUS';
$JOBS_CREATEDON = 'CREATEDON';
$JOBS_MODIFIEDON = 'MODIFIEDON';
$JOBS_MODIFIEDBY = 'MODIFIEDBY';
$JOBS_REASON = 'REASON';
$JOBS_JOBTYPE = 'JOBTYPE';
$JOBS_JOBCATEGORY = 'JOBCATEGORY';


$JOBCATEGORY_TABLE = 'JOBCATEGORY';

$JOBCATEGORY_CATEGORYID = 'CATEGORYID';
$JOBCATEGORY_CATEGORYDESCRIPTION = 'CATEGORYDESCRIPTION';


$SECURITYQUEST_TABLE = 'SECURITYQUESTION';

$SECURITYQUEST_SECQUESTID = 'SECQUESTIONID';
$SECURITYQUEST_SECQUESTDESCRIPTION = 'SECQUESTIONDESCRIPTION';





$RESUME_TABLE = 'RESUME';

$RESUME_JOBSKID = 'JOBSKID';
$RESUME_FULLNAME = 'FULLNAME';
$RESUME_FATHERNAME = 'FATHERNAME';
$RESUME_MOTHERNAME = 'MOTHERNAME';
$RESUME_DOB = 'DOB';
$RESUME_PHOTOFORRESUME = 'PHOTOFORRESUME';
$RESUME_ADDITLINFO = 'ADDITLINFO';
$RESUME_CAREEROBJECTIVE = 'CAREEROBJECTIVE';
$RESUME_CURRENTCOMPANYNAME = 'CURRENTCOMPANYNAME';
$RESUME_CURRENTDESIGNATION = 'CURRENTDESIGNATION';
$RESUME_CURRENTJOININGDATE = 'CURRENTJOININGDATE';
$RESUME_CURRENTRESIGNDATE = 'CURRENTRESIGNDATE';
$RESUME_CURRENTCOMPANYDESC = 'CURRENTCOMPANYDESC';
$RESUME_PREVIOUSCOMPANYNAME = 'PREVIOUSCOMPANYNAME';
$RESUME_PREVIOUSDESIGNATION = 'PREVIOUSDESIGNATION';
$RESUME_PREVIOUSJOININGDATE = 'PREVIOUSJOININGDATE';
$RESUME_PREVIOUSRESIGNDATE = 'PREVIOUSRESIGNDATE';
$RESUME_PREVIOUSCOMPANYDESC = 'PREVIOUSCOMPANYDESC';
$RESUME_SSCPERCENT = 'SSCPERCENT';
$RESUME_HSCPERCENT = 'HSCPERCENT';
$RESUME_BACHELORDEGPERCENT = 'BACHELORDEGPERCENT';
$RESUME_DEGREETYPE = 'DEGREETYPE';
$RESUME_BACHELORCOURSEID = 'BACHELORCOURSEID';
$RESUME_MASTERCOURSEID = 'MASTERCOURSEID';
$RESUME_MASTERDEGPERCENT = 'MASTERDEGPERCENT';
$RESUME_KEYSKILLS = 'KEYSKILLS';
$RESUME_PRIMARYLANGUAGE = 'PRIMARYLANGUAGE';
$RESUME_SECONDARYLANGUAGE = 'SECONDARYLANGUAGE';
$RESUME_TERTIARYLANGUAGE = 'TERTIARYLANGUAGE';


$COURSE_TABLE = 'COURSE';

$COURSE_COURSEID = 'COURSEID';
$COURSE_COURSETYPE = 'COURSETYPE';
$COURSE_COURSENAME = 'COURSENAME';

$COURSETYPE_MASTER = '2';
$COURSETYPE_BACHELOR = '2';



//Consultant Table 27-Oct-17 : Pravin
$CONSULTANT_TABLE = 'CONSULTANT';

$CONSULTANT_CONSULTANTID = 'CONSULTANTID';
$CONSULTANT_FNAME = 'FNAME';
$CONSULTANT_MNAME = 'MNAME';
$CONSULTANT_LASTNAME = 'LASTNAME';
$CONSULTANT_ADDRESS1 = 'ADDRESS1';
$CONSULTANT_ADDRESS2 = 'ADDRESS2';
$CONSULTANT_CITY = 'CITY';
$CONSULTANT_STATE = 'STATE';
$CONSULTANT_POSTALCODE = 'POSTALCODE';
$CONSULTANT_COUNTRY = 'COUNTRY';
$CONSULTANT_PHONE1 = 'PHONE1';
$CONSULTANT_PHONE2 = 'PHONE2';
$CONSULTANT_FAXNO = 'FAXNO';
$CONSULTANT_CREATEDON = 'CREATEDON';
$CONSULTANT_MODIFIEDON = 'MODIFIEDON';
$CONSULTANT_MODIFIEDBY = 'MODIFIEDBY';

$sessionConsultantId = 'CONSULTANT';

$JOBSEEKERTYPE = '4';
$EMPLOYERTYPE = '3';
$CONSULTANTTYPE = '5';

//Consultant Table 27-Oct-17 : Pravin


//Session check variables

$sessionJobSeekerId = 'JOBSEEKERID';
$sessionEmployerId = 'EMPLOYERID';
$sessionUserType = 'TYPE';
$sessionForgotPwd = 'USERID_AT_FORGOTPWD';
$sessUserEmailAtNewPassword = 'SESSUSEREMAILATNEWPASSWORD';
$sessUserEmailAtProcessForgotPwd = 'SESSUSEREMAILATPROCESSFORGOTPWD';


$LOGINSTATUSACTIVE = '1';
$LOGINSTATUSDISABLE = '2';

?>